Filter out not application targets
artemnovichkov/Carting pull request #31
Opened 2018-11-02 11:23 UTC by alphatroya

Close #30

2018-11-06 16:06 UTC, artemnovichkov requested changes

2018-11-06 16:06 UTC, artemnovichkov commented on Sources/CartingCore/Models/TargetBody.swift
> +struct ProductType {
Please, move the struct to different file

2018-11-06 16:06 UTC, artemnovichkov commented on Sources/CartingCore/Models/TargetBody.swift
> +    init(_ value: String) {
According to Swift Style Guide:
```suggestion
    init(value: String) {
```

2018-11-06 16:06 UTC, artemnovichkov commented
Why didn't you add an enum? For instance:
```swift
enum ProductType {
    case application
    case other
}
```
I guess it's more flexible and will give a possibility to extend with different checks

2018-11-07 07:19 UTC, alphatroya commented
> Why didn't you add an enum? For instance:
> 
> ```swift
> enum ProductType {
>     case application
>     case other
> }
> ```
> 
> I guess it's more flexible and will give a possibility to extend with different checks

I think about it. But other case should store value variable for `description` property hence we should throw up `String` inheritance and blow up implementation

``` swift
enum ProductType {

    case application
    case other(value: String)

    private static let applicationRawValue = "\"com.apple.product-type.application\""

    init(value: String) {
        switch value {
        case ProductType.applicationRawValue:
            self = .application
        default:
            self = .other(value: value)
        }
    }

    var description: String {
        switch self {
        case .application:
            return ProductType.applicationRawValue
        case let .other(value):
            return value
        }
    }

    var isApplication: Bool {
        switch self {
        case .application:
            return true
        default:
            return false
        }
    }
}
```

2018-11-07 08:16 UTC, artemnovichkov commented
I agree, good point! The last comment - could we format `"\"com.apple.product-type.application\""` string by trimming `\"` symbols?

2018-11-07 13:16 UTC, alphatroya commented
> I agree, good point! The last comment - could we format `"\"com.apple.product-type.application\""` string by trimming `\"` symbols?

I think that solution will be enought

2018-11-07 14:20 UTC, artemnovichkov commented
Thank you!

2018-11-07 14:20 UTC, merged